### ISSUE TITLE
Improve generating tests

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#1679]
To improve how tests are generated, and to alleviate some of the pains and confusions that Pester v5 brought there should be few things added that work together: 

- [x] allow testcases to take any array, this will define $_ variable inside the block / test scope, which will be available in all the setups, blocks and teardowns.  If the collection single item is IDictionary ( e.g. hashtable) additionally splat this into variables as `-TestCases` does now #1628

- [x] add -ForEach to Describe, Context and It which will have the behavior of -TestCases to allow parametrized blocks #832

- [x] expand block and test names in their respective scopes, make sure to expand `<_>` to value of `$_`
- [x] expand dot notation in block and test names `user.name` -> `$user.Name`

- [x] When Detailed or Diagnostic output is used write Describe / Context later to use the Expanded name that is not expanded until after BeforeAll, fallback to Name

- [x] Generate nothing when TestCases is specified and is null or empty  https://github.com/pester/Pester/issues/1682

```powershell
$files = Get-Item 'file1.ps1', 'file2.ps1', 'file3.ps1' 
$scenarios = @(
    @{ inputValue = 1; expected = $true }, @{ inputValue = 3; expected = $false }
    @{ inputValue = 4; expected = $false }, @{ inputValue = 5; expected = $false }
)

# -ForEach parameter would be added to Describe and Context
# and also to It where it would be aliased to TestCases. 
# It would not only array of hastables but any array, unlike the current -TestCase with this behavior: 
#  Each item is assigned to $_ variable, if the input array is an array of IDictionary (e.g. array of hastables)
#  it would additionally define each key as a variable (as it happens with TestCases in It right now)
Describe "Fake Tests" -ForEach $files {

    BeforeAll {
        $file = $_

        # source file once for all these tests
        . $file
    }

    # this should expand to the result of "$_"    
    It "<_> : <inputValue> should return <expected>" -TestCases $scenarios {
        ($inputValue -eq 1) | Should -eq $expected
    }

    # this should expand to the result of "$file"    
    It "<file> : <inputValue> is an integer" -TestCases $scenarios {
        $inputValue | Should -BeOfType [int]
    }

    # this should expand to the result of "$($file.FullName)"
    It "<file.FullName> : <inputValue> should return <expected>" -TestCases $scenarios {
        ($inputValue -eq 1) | Should -eq $expected
    }
}
```

Related #1564

**Comment by nohwnd** [comment]
@vexx32 ^^^ comment pls

**Comment by JPRuskin** [comment]
Sounds like useful additions.

**Comment by vexx32** [comment]
👀

That looks really nice!

**Comment by nohwnd** [comment]
> The only unexpected thing is perhaps that you can define arbitrary variables in a BeforeAll and then use them as though they were from a -ForEach / -TestCases input.

Which line in the example do you refer to? Is it expanding <file> from the $file ? That is because people want to be able to do stuff like this: 

```powershell
# pester v4
Describe "bla" {
  foreach ($file in $files) { 
    It "$file - some test" { 
    }
}
```
And this:
```powershell
# pester v4
BeforeAll { 
     $file = (generate filename in temp)
}

It "collects stuff and outputs report into $file" { 
    Collect-Stuff -Destination $file
}
```

**Comment by nohwnd** [comment]
One more thing to think about is where exactly the name pattern should expand, would you expect variables from BeforeEach to be available? I guess you would? Maybe expanding it after It, or even after AfterEach would be even better? 

```powershell
BeforeEach { 
    $file = "foo"
} 

It "<file> test" { 
    $file = "bar"
}

AfterEach { 
    $file = "baz"
}
```
Should the test be named "foo test", "bar test", or "baz test"?

**Comment by nohwnd** [comment]
Discussed on Slack, expanding it after Before* but before It is the way to go, to keep it work like actual powershell variable scoping.

**Comment by hbuckle** [comment]
What's the vision for how this will fit in with the `New-TestContainer` functionality?

**Comment by nohwnd** [comment]
@hbuckle you will be able to pass the values to script, and because script defines them before Discovery and also before Run you will be able to use them in your test cases. e.g. like this: 


```powershell
$scenarios = @(
    @{
        Scenario = @{
            Name = "A"
            Examples = @(
                @{ User = @{ Name = "Jakub"; Age = 31 } }
                @{ User = @{ Name = "Tomas"; Age = 27 } }
            )
        }
    }
    @{
        Scenario = @{
            Name = "B"
            Examples = @(
                @{ User = @{ Name = "Jane"; Age = 25 } }
            )
        }
    }
)

$sb = {
    param ($Scenario)

    Describe "Scenario - <name>" -ForEach $Scenario {

        It "Example - <user.name> with age <user.age> is less than 35" -ForEach $Examples {
            $User.Age | Should -BeLessOrEqual 35
        }
    }
}

$container = New-TestContainer -ScriptBlock $sb -Data $scenarios

$r = Invoke-Pester -Container $container -PassThru -Output Detailed
$r.Containers[0].Blocks[0].ExpandedName | Verify-Equal "Scenario - A"
$r.Containers[0].Blocks[0].Tests[0].ExpandedName | Verify-Equal "Example - Jakub with age 31 is less than 35"
```

**Comment by asears** [comment]
Could the custom attribute feature and some binding option could be used to make a test with similar premise as what is in Nunit TestCaseAttribute?  Rather than instantiating a new TestContainer and using foreach, use attributes and let the Pester Framework instantiate internally / iterate internally?  Probably some other uses for defining attributes in Pester rather than passing as parameters in describes.  

I think there are some custom attributes already being defined, though can't find them in the docs.
The attribute & its parameters could be discovered via Invoke-Pester command?

Here's the example I leveraged in past with Nunit as an example.
https://docs.nunit.org/articles/nunit/writing-tests/attributes/testcase.html

A few links which may be relevant to parameterized testing.  I found the load test data from psd1 an _interesting_ option and some custom attributes which could be included as default in Pester?

https://powershellexplained.com/2017-02-19-Powershell-custom-attribute-validator-transform/
https://powershellexplained.com/2017-02-20-Powershell-creating-parameter-validators-and-transforms/
https://powershell.one/powershell-internals/attributes/custom-attributes

Another example of passing parameters in as custom attributes.
https://github.com/omniomi/Check-It

Might get rid of the foreach in the test, at least in some scenarios where you just want to create a multi-parameter-driven test with same structure and different parameters.  This improvement looks very useful either way!

**Comment by nohwnd** [comment]
@asears  are you talking about the code in this comment https://github.com/pester/Pester/issues/1679#issuecomment-689526668 or about the idea in general? 

How is the NUnit stuff different the -TestCases that we have now?  (Except that it has a magical ExpectedResult parameter that asserts on the result. 

The example I show in the comment is trying to show how you could do it if you had a set of data externally (people like @mczerniawski / @rchaganti have that in their infra testing modules I think). And tries to show everything that would be possible. 

But you can still just provide a hashtable or array of examples to Describe, as you would be providing hashtable or array of examples to It. Like this: 

```powershell 
Describe "File - <_>" -ForEach @(
    "$PSScriptRoot/src/abc.ps1"
    "$PSScriptRoot/src/def.ps1"
) {
    It "Is not empty" {
        $_ | Should -Exist
    }

    It "Ends with }" {
        Get-Content  $_ | Select -Last 1 | Should -Be "}"
    }
}
```

```shell
Starting discovery in 1 files.
Discovering in C:\t\filechecks\filechecks.tests.ps1.
Found 4 tests. 41ms
Discovery finished in 49ms.

Running tests from 'C:\t\filechecks\filechecks.tests.ps1'
Describing File - C:\t\filechecks\src\abc.ps1
  [+] Is not empty 21ms (18ms|3ms)
  [+] Ends with } 19ms (18ms|1ms)

Describing File - C:\t\filechecks\src\def.ps1
  [+] Is not empty 5ms (3ms|2ms)
  [+] Ends with } 4ms (3ms|1ms)
Tests completed in 370ms
Tests Passed: 4, Failed: 0, Skipped: 0 NotRun: 0
```

**Comment by hbuckle** [comment]
What's the difference between passing the scenarios in as a parameter with New-TestContainer and just defining them inline before Describe like in your first post?

**Comment by nohwnd** [comment]
Very little, but in some cases you want your data provided to be dynamic, for example you have a set a desired configuration that you load from a DB as a big JSON. And then you run it against 100 different computers to see which ones are setup correctly. You want to pass the config and the computer to the test externally and you can do that via the New-TestContainer. 

Or in simpler cases you can just inline the data in the file, or gather the data in the file (say instead of `$files = "abc.ps1", "def.ps1"` you would do `$files = Get-ChildItem -File -Filter *.ps1 -Path "$PSScriptRoot/filesToCheck/" `.

**Comment by vexx32** [comment]
@nohwnd might be a good idea to clarify in docs for this feature what happens if you use the hashtable splatting functionality and use `"_"` as one of the testcases parameter keys; i.e., you'd have `param($_)` in the tests. Naturally that shouldn't be done, really, but would be good to document exactly what the behaviour there will be.
