### ISSUE TITLE
Add description to all should-* assertions and remove this todo

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#2498]
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### What is the issue?

https://github.com/fflaten/Pester/blob/aa7f319d9c438ba6f66346bf7b9c7c2ff34ef397/tst/Help.Tests.ps1#L27

### Expected Behavior

todo is gone

**Comment by nohwnd** [comment]
duplicate #2490
